### ISSUE TITLE
Alignement crosshair weirdness

### ISSUE THREAD

**Issue by Socapex** [Pixen/Pixen#248]
To reproduce: Open 2 files, edit second file and bring back focus to first file window. Hover mouse over preview window and come back to edit window. Alignment crosshair not aligned anymore.

Second weirdness: Click preview window, then click toolbar on edit window. Alignement crosshair stuck.

These aren't too serious, but it may point to some weird stuff going on. Video demonstration:
http://tinypic.com/r/6ir3nn/6

**Comment by mattrajca** [comment]
I can't reproduce this in Pixen 3.8.1
