### ISSUE TITLE
Clicking on other windows ignores keyboard shortcuts. 

### ISSUE THREAD

**Issue by johnfn** [Pixen/Pixen#253]
This might seem incredibly picky, but having focus on any window other than the drawing window ignores keyboard shortcuts also. For instance, clicking on the toolbar or the color picker will lose focus. The expected behavior is to accept keyboard shortcuts unilaterally.

**Comment by pixelsyntax** [comment]
This is still an issue in 3.8.1 and is causing me much sadness :(

**Comment by mattrajca** [comment]
This has been fixed for the next release of Pixen.
