### ISSUE TITLE
Selection border does not display when working under certain layers

### ISSUE THREAD

**Issue by ltucker** [Pixen/Pixen#262]
In 3.5.7b2 if I use the rectangular selection tool in the attached image on the layer "Draw selection on this layer" with the layer "Grid Guide" visible, the selection border does not display.   If the layer "Grid Guide" is made invisible, the border will display as expected.

(also applies to other selection tools)

https://s3.amazonaws.com/voxluci/selection_bug.pxi

**Comment by mattrajca** [comment]
This has been fixed for the next release of Pixen.
