### ISSUE TITLE
Option: Drawing on pixels with same color as foreground color erases them

### ISSUE THREAD

**Issue by hced** [Pixen/Pixen#277]
I've seen this feature in some pixel editors which I forgot the names of. Nonetheless, it's actually a real killer feature:

=> Drawing on pixels that has the same color as your foreground color erases them.

Admittedly, Pixen's right-click tool where you can assign Erase for e.g. right-click, defeats the lack of this functionality to some degree. But I think 1) it would be a time saver to be able to only erase pixels of any given color with my suggestion, and 2) it would be nice to have something else than Erase assigned to right-click for quickly erasing.

N.B. It should be noted that this operation should only activate IF the pixel you started drawing on was of the same color as foreground color. Otherwise, this behavior will be skipped.

**Comment by mattrajca** [comment]
Very few requests for this since it was suggested over two years ago. Closing for now.
