### ISSUE TITLE
Color picker / Eyedropper tool do not agree

### ISSUE THREAD

**Issue by ltucker** [Pixen/Pixen#298]
Using Pixen 3.5.17

If you select a color, draw with it and resample it, it changes -- maybe something to do with Device / Generic RGB when sampling?

Close Pixen and reopen
Create a new image
Select the "Colors" Dialog
Select Color Sliders / HSB Sliders
Enter Hue 100, Saturation 100, Brightness 50
(This should also modify the left tool color well)
Select the "Fill" Tool and fill the canvas with the color
Select the "Eyedropper" Tool and sample the color
The "Color" dialog slider values change (in my case to 101 / 98 / 44 )
The color well in the "Colors" dialog has the tool tip "Generic RGB" 

This also appears to happen for the "Magnifying Glass" in the color dialog. 

For reference I'm using a Macbook Air, the primary display has the display profile "Color LCD"

**Comment by mattrajca** [comment]
It is possible for different sets of HSV values to correspond to the same color in RGB. Since this is ambiguous, the color picker may display different HSV for what is actually the same color.
