### ISSUE TITLE
"Save as.." filename1 also overwrites filename2

### ISSUE THREAD

**Issue by prewk** [Pixen/Pixen#311]
I open `file1.png`, perform some changes, "Save as.." `file2.png`. Suddenly, the editor _also_ saves the `file1.png` so both files change and the original `file1.png` is lost.

**Comment by mattrajca** [comment]
You need to uncheck the "Keep changes in original document" checkbox.

![screen shot 2015-11-01 at 2 49 34 pm](https://cloud.githubusercontent.com/assets/123372/10871266/ced1ba0e-80a7-11e5-9f23-db46c8e0129b.png)

**Comment by prewk** [comment]
Thanks, I didn't see that checkbox.
