### ISSUE TITLE
Undo undoes way too much

### ISSUE THREAD

**Issue by pepijndevos** [Pixen/Pixen#313]
Try this:

1. Make a new animation
2. Draw a few things
3. Add a frame
4. Repeat 2 and 3. a few more times
5. Hit `CTRL+Z`

Instead of undoing the things you drew on the last frame, it deletes all the frames you just made.
I started using Pixen a few hours ago and I'm ready to give up again after losing work a few times in a row in the following way:

1. Draw a frame
2. Repeat
4. Mess up badly
5. Hit `CTRL+Z`
6. Lose everything
7. Hit `CTRL+R` to messed up state and redraw entire frame

**Comment by mattrajca** [comment]
Which version of Pixen are you running?

**Comment by pepijndevos** [comment]
3.8.1
